#  _______ _     _         _____
# |__   __(_)   | |       / ____|
#    | |   _  __| | ___  | |  __  __ _ _   _  __ _  ___
#    | |  | |/ _` |/ _ \ | | |_ |/ _` | | | |/ _` |/ _ \
#    | |  | | (_| |  __/ | |__| | (_| | |_| | (_| |  __/
#    |_|  |_|\__,_|\___|  \_____|\__,_|\__,_|\__, |\___|
#                                             __/ |
#                                            |___/
# Author: Bryce Kellogg (bryce@kellogg.org)
# Copyright: 2023 Bryce Kellogg
# License: GPLv3
#
# A Cloudformation sub-template for the database infrastructure.
#
# All persistent data storage for the tide guage cloud infrastructure is
# stored in AWS DynamoDB tables. The database uses the schema descibed below:
#
# Data Table:
#
#    +------------+-----------+-----+
#    | devicename | timestamp | ... |
#    |    <str>   |   <int>   |     |
#    +------------+-----------+-----+
#
#    The "Data Table" is used to store all time series data in the system. Each
#    record/row is identified by the composite primary key (devicename, timestamp),
#    where devicename is the partition key & timestamp is the sort key. The other
#    attributes in a given record correspond to the data for that timestamp
#    for that specific device.
#
# Current Config Table
#
#    +------------+-----+
#    | devicename | ... |
#    |    <str>   |     |
#    +------------+-----+
#
#    The "Config Table" is used to represent the current state of various config
#    options. Each record/row is identified by a primary partition key devicename
#    that corresponds to a single device. The other attributes describe the current
#    state of that device.
#
# These two tables can be referenced via tables name:
#    - <StackName>-data-table
#    - <StackName>-config-table
#
# The values and formats of non-key attributes are defined elsewhere.
#
Resources:

  DataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: "PAY_PER_REQUEST"
      TableName: !Join ['-', [!Ref AWS::StackName, 'data-table']]
      AttributeDefinitions:
        - {AttributeName: "devicename", AttributeType: "S"}
        - {AttributeName: "timestamp", AttributeType: "N"}
      KeySchema:
        - {AttributeName: "devicename", KeyType: "HASH"}
        - {AttributeName: "timestamp", KeyType: "RANGE"}

  ConfigTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: "PAY_PER_REQUEST"
      TableName: !Join ['-', [!Ref AWS::StackName, 'config-table']]
      AttributeDefinitions:
        - {AttributeName: "devicename", AttributeType: "S"}
      KeySchema:
        - {AttributeName: "devicename", KeyType: "HASH"}
